## 03_주가 관련 보조지표를 활용한 등락예측_신세계

In [2]:
# 기본적으로 필요한 라이브러리
import numpy as np
import pandas as pd


#시각화 라이브러리
import matplotlib.pyplot as plt 
import seaborn as sns

#datetime 형식으로 바꿔주는 라이브러리
from datetime import datetime

In [5]:
stock = pd.read_csv('kakao.csv')
stock.head()

FileNotFoundError: [Errno 2] No such file or directory: 'kakao.csv'

In [3]:
stock = stock.set_index('Date') # date를 index로 설정
stock = stock.loc['2020-09-01' : '2021-06-30']

In [4]:
stock_train = stock.iloc[:-1]
target = stock_train['fluct_grade']
stock_train = stock_train.drop('fluct_grade', axis = 1)

from sklearn.model_selection import train_test_split
train, test, train_target, test_target = train_test_split(
    stock_train, target, test_size=0.3, shuffle=False)

In [5]:
# Importing Classifier Modules
import warnings
warnings.filterwarnings(action='ignore')

from sklearn.linear_model import LogisticRegression   # logistic
from sklearn.neighbors import KNeighborsClassifier   # knn
from sklearn.naive_bayes import GaussianNB   # naive
from lightgbm import LGBMClassifier   # lightGBM
from sklearn import datasets
from sklearn import metrics

In [6]:
# 모형 생성
import lightgbm as lgb
logistic = LogisticRegression()
knn = KNeighborsClassifier()
naive = GaussianNB()
lgb = lgb.LGBMClassifier()

models = [{'name' : 'Logistic', 'model' : logistic}, {'name' : 'KNN', 'model' : knn},
          {'name' : 'lgb.LGBM', 'model' : lgb}, {'name' : 'NaiveBayes', 'model' : naive}]

for m in models : 
    model = m['model']
    model.fit(train, train_target)
    
    predicted = model.predict(test)

#Accuracy : 전체 샘플 중 맞게 예측한 샘플수의 비율
#Precision(정밀도) : postive라고 예측한 것 중에서 실제 postive인 것
#Recall(재현율) : 실제 postive중에 예측한 postive 비율
    print ('model name : {}'.format(m['name']))
    print (metrics.classification_report(test_target, predicted))

#confusion_matrix에서
#행은 실제값, 열은 예측한 값으로 0 1 순서대로 임
    print('Confusion Matrix') 
    print (metrics.confusion_matrix (test_target, predicted))

    print ('Accuracy Score : {:.4f}\n'.format(metrics.accuracy_score(test_target, predicted)))

model name : Logistic
              precision    recall  f1-score   support

           1       1.00      0.29      0.44         7
           2       0.74      0.74      0.74        19
           3       0.78      0.96      0.86        26
           4       0.83      0.62      0.71         8
           5       0.00      0.00      0.00         1

    accuracy                           0.75        61
   macro avg       0.67      0.52      0.55        61
weighted avg       0.79      0.75      0.74        61

Confusion Matrix
[[ 2  4  0  0  1]
 [ 0 14  5  0  0]
 [ 0  0 25  0  1]
 [ 0  1  2  5  0]
 [ 0  0  0  1  0]]
Accuracy Score : 0.7541

model name : KNN
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         7
           2       0.25      0.11      0.15        19
           3       0.40      0.73      0.52        26
           4       0.00      0.00      0.00         8
           5       0.00      0.00      0.00         1

    accuracy 