# 순환신경망(RNN)
- 순환 신경망(Recurrent Neural Network)은 은닉 계층 안에 하나 이상의 순환 계층을 갖는 신경망을 의미
- 순환 신경망은 다른 네트워크들과 입력을 받는 방식에서 다르다. 순서가 있는 데이터에 주로 사용되며, 해당 데이터를 입력으로, 하나의 네트워크를 통해서 순서대로 출력을 얻는다.
- 순서가 있는 데이터는 소리, 언어, 날씨, 주가 등의 데이터처럼 시간의 변화에 함께 변화하면서 그 영향을 받는 데이터를 의미

## 순환계층
- 시계열 데이터 처리에 알맞게 고안된 퍼셉트론 계층
- 가중치와 편향을 각 시간대 데이터에 반복해서 사용
- 순환 벡터를 사용하여 정보를 전달

## - SimpleRNN 네트워크 예제
[0.0 0.1 0.2 0.3]이라는 0.1씩 늘어나는 수열을 줄 때, 이후의 값들도 예측하는 네트워크

In [1]:
# test 환경
import numpy as np

X = []
Y = []
for i in range(6):
    lst = list(range(i,i+4))
    X.append(list(map(lambda c: [c/10], lst)))
    Y.append((i+4)/10)
X = np.array(X)
Y = np.array(Y)
print(X)
print(Y)

[[[0. ]
  [0.1]
  [0.2]
  [0.3]]

 [[0.1]
  [0.2]
  [0.3]
  [0.4]]

 [[0.2]
  [0.3]
  [0.4]
  [0.5]]

 [[0.3]
  [0.4]
  [0.5]
  [0.6]]

 [[0.4]
  [0.5]
  [0.6]
  [0.7]]

 [[0.5]
  [0.6]
  [0.7]
  [0.8]]]
[0.4 0.5 0.6 0.7 0.8 0.9]


In [16]:
# 모델 만들기 & 학습
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model = Sequential([SimpleRNN(units=32,
              # units 파라미터는 RNN 신경망에 존재하는 뉴런의 개수
                    return_sequences=False,
        # RNN 계산 과정에 있는 hidden state를 출력할 것인지에 대한 값을 의미
        # 해당 값은 다층으로 이루어진 RNN 또는 one-to-many, many-to-many 출력을 위해서 사용
        # False의 경우, 마지막 출력값 하나를 출력/ True의 경우, 모든 과정의 출력 값을 출력
                    input_shape=[4,1]),
                    Dense(1, activation='tanh')])
# 모델은 Sequential에 simpleRNN과 Dense레이어를 하나씩 추가
# input_shape는 4 time-step마다 하나의 답이라서 [4,1] 선언
# 학습을 반복하면서 mse 값을 낮추는 훈련 함

model.compile(optimizer='adam',
              loss='mse',
              metrics=['accuracy'])

history = model.fit(X, Y, epochs=200, verbose=0)

In [17]:
# 기존의 훈련 데이터 세트를 넣어서 예측
print(model.predict(X))

[[0.3674551 ]
 [0.51891965]
 [0.6376259 ]
 [0.7262246 ]
 [0.79056275]
 [0.8367987 ]]


In [18]:
# 1.2에 많이 가깝진 않지만 훈련데이터를 증가시켜서 해당 결과를 개선시킬 수 있음
X_test = np.array([[[0.8],[0.9],[1.0],[1.1]]])
print(model.predict(X_test))

[[0.9120052]]
